/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfasGrafica;

import Auxiliar.Serializador;
import Dominio.Juego;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mjpla
 */
public class VentInicio extends javax.swing.JFrame {
    private Juego elJuego;

    
    /**
     * Creates new form VentInicio
     */
    
    public VentInicio(Juego iJuego) {
        
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.elJuego = iJuego;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipial = new javax.swing.JPanel();
        btnRegJugador = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnArchivosJugadores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stones");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("VentanaInicio"); // NOI18N
        setSize(new java.awt.Dimension(300, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        btnRegJugador.setText("Registro de Jugador");
        btnRegJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegJugadorActionPerformed(evt);
            }
        });

        btnJugar.setText("Jugar Partida");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        jButton1.setText("Ranking de Jugadores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnArchivosJugadores.setText("Cargar Archivo de Jugadores");
        btnArchivosJugadores.setName(""); // NOI18N
        btnArchivosJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivosJugadoresActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stones.png"))); // NOI18N

        javax.swing.GroupLayout panelPrincipialLayout = new javax.swing.GroupLayout(panelPrincipial);
        panelPrincipial.setLayout(panelPrincipialLayout);
        panelPrincipialLayout.setHorizontalGroup(
            panelPrincipialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipialLayout.createSequentialGroup()
                .addGroup(panelPrincipialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipialLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(panelPrincipialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnArchivosJugadores)))
                    .addGroup(panelPrincipialLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        panelPrincipialLayout.setVerticalGroup(
            panelPrincipialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegJugador)
                .addGap(18, 18, 18)
                .addComponent(btnJugar)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btnArchivosJugadores)
                .addGap(26, 26, 26))
        );

        getContentPane().add(panelPrincipial);
        panelPrincipial.setBounds(0, 0, 404, 290);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegJugadorActionPerformed
        // TODO add your handling code here:
        VentJugador vJugador = new VentJugador(elJuego);
       vJugador.setVisible(true);
    }//GEN-LAST:event_btnRegJugadorActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        if (!this.elJuego.getJugadores().isEmpty()){
            VentTipoTablero vTipoTablero = new VentTipoTablero(elJuego);
            vTipoTablero.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "No hay jugadores ingresados para comenzar una partida.", "" + "Ingreso de datos", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnJugarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VentRanking vRanking = new VentRanking(elJuego);
        vRanking.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnArchivosJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivosJugadoresActionPerformed
        // TODO add your handling code here:
        //cargar archivo
        int resultado;
        File fichero;
        VentBrowser ventana = new VentBrowser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("solo archivos de texto","txt");
        ventana.jfcCargarArchivos.setFileFilter(filtro);
        resultado = ventana.jfcCargarArchivos.showOpenDialog(null);
        
        if (JFileChooser.APPROVE_OPTION == resultado) {
            fichero = ventana.jfcCargarArchivos.getSelectedFile();
            if((fichero.toString().contains(".txt")) || (fichero.toString().contains(".TXT"))){
            int [] cantLeidos = this.elJuego.cargarArchivoJugadores(fichero.toString());
            JOptionPane.showMessageDialog(null, "Se cargaron "+cantLeidos[0]+" Jugadores \n Cantidad de lines con error: "+cantLeidos[1],"Archivo aceptado",1);       
            }
            else{
             JOptionPane.showMessageDialog(null, "Solamente se aceptan archivos txt.\n Cada linea con el siguiente formato: Nombre#edad#alias","Error al cargr archivo",0);
            }
        }
        
    }//GEN-LAST:event_btnArchivosJugadoresActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        //this.elJuego.Guardar();
        try {
            Serializador.Guardar(this.elJuego, "DatosGuardados");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage() + "|" + e.getStackTrace(), "" + "Ingreso de datos", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivosJugadores;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnRegJugador;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelPrincipial;
    // End of variables declaration//GEN-END:variables
}
