/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfasGrafica;

import java.awt.Dimension;
import prog2SO.Juego;

/**
 *
 * @author mjpla
 */

public class VentTipoTablero extends javax.swing.JFrame {
    private VentPartida vPartida;
    private Juego miJuego;
    /**
     * Creates new form VentTipoTablero
     */
    public VentTipoTablero(Juego iJuego) {
        
        initComponents();
        this.setSize(new Dimension(300,300));
        miJuego=iJuego;
        vPartida = new VentPartida(iJuego);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     **/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTipoTablero = new javax.swing.JPanel();
        btnPorDefecto = new javax.swing.JButton();
        btnRandom = new javax.swing.JButton();

        setTitle("Seleccionar Tablero");
        setResizable(false);
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        btnPorDefecto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPorDefecto.setText("Tablero por Defecto");
        btnPorDefecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorDefectoActionPerformed(evt);
            }
        });

        btnRandom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRandom.setText("Tablero Random");
        btnRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTipoTableroLayout = new javax.swing.GroupLayout(panelTipoTablero);
        panelTipoTablero.setLayout(panelTipoTableroLayout);
        panelTipoTableroLayout.setHorizontalGroup(
            panelTipoTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoTableroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelTipoTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPorDefecto))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        panelTipoTableroLayout.setVerticalGroup(
            panelTipoTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTipoTableroLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnPorDefecto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        getContentPane().add(panelTipoTablero);
        panelTipoTablero.setBounds(20, 8, 290, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPorDefectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorDefectoActionPerformed
        // TODO add your handling code here:
       this.miJuego.setEsGenerico(true);
       this.vPartida.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnPorDefectoActionPerformed

    private void btnRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionPerformed
        // TODO add your handling code here:
         this.miJuego.setEsGenerico(false);
         this.vPartida.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_btnRandomActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentTipoTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentTipoTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentTipoTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentTipoTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentTipoTablero().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPorDefecto;
    private javax.swing.JButton btnRandom;
    private javax.swing.JPanel panelTipoTablero;
    // End of variables declaration//GEN-END:variables
}
