/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfasGrafica;

import Auxiliar.Serializador;
import Dominio.Juego;
import com.sun.media.jfxmedia.logging.Logger;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mjpla
 */
public class VentInicio extends javax.swing.JFrame {
    private Juego elJuego;

    
    /**
     * Creates new form VentInicio
     */
    
    public VentInicio(Juego iJuego) {
        
        initComponents();
        this.elJuego = iJuego;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipial = new javax.swing.JPanel();
        btnRegJugador = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnArchivosJugadores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("VentanaInicio"); // NOI18N
        setSize(new java.awt.Dimension(300, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        btnRegJugador.setText("Registro de Jugador");
        btnRegJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegJugadorActionPerformed(evt);
            }
        });

        btnJugar.setText("Jugar Partida");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        jButton1.setText("Ranking de Jugadores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnArchivosJugadores.setText("Cargar Archivo de Jugadores");
        btnArchivosJugadores.setName(""); // NOI18N
        btnArchivosJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivosJugadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipialLayout = new javax.swing.GroupLayout(panelPrincipial);
        panelPrincipial.setLayout(panelPrincipialLayout);
        panelPrincipialLayout.setHorizontalGroup(
            panelPrincipialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipialLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(panelPrincipialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnArchivosJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        panelPrincipialLayout.setVerticalGroup(
            panelPrincipialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipialLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnRegJugador)
                .addGap(18, 18, 18)
                .addComponent(btnJugar)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btnArchivosJugadores)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        getContentPane().add(panelPrincipial);
        panelPrincipial.setBounds(0, 20, 380, 246);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegJugadorActionPerformed
        // TODO add your handling code here:
        VentJugador vJugador = new VentJugador(elJuego);
       vJugador.setVisible(true);
    }//GEN-LAST:event_btnRegJugadorActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        if (!this.elJuego.getJugadores().isEmpty()){
            VentTipoTablero vTipoTablero = new VentTipoTablero(elJuego);
            vTipoTablero.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "No hay jugadores infresados para comenzar una partida.", "" + "Ingreso de datos", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnJugarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VentRanking vRanking = new VentRanking(elJuego);
        vRanking.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnArchivosJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivosJugadoresActionPerformed
        // TODO add your handling code here:
        //cargar archivo
        int resultado;
        File fichero;
        VentBrowser ventana = new VentBrowser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("solo archivos de texto","txt");
        ventana.jfcCargarArchivos.setFileFilter(filtro);
        resultado = ventana.jfcCargarArchivos.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == resultado) {
            fichero = ventana.jfcCargarArchivos.getSelectedFile();
            int [] cantLeidos = this.elJuego.cargarArchivoJugadores(fichero.toString());
            JOptionPane.showMessageDialog(null, "Se cargaron "+cantLeidos[0]+" Jugadores \n Cantidad de lines con error:"+cantLeidos[1]);
        }
        
    }//GEN-LAST:event_btnArchivosJugadoresActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        //this.elJuego.Guardar();
        try {
            Serializador.Guardar(this.elJuego, "DatosGuardados");
        } catch (IOException e) {
            //Que hacemos
        }
        
    }//GEN-LAST:event_formWindowClosing

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                //new VentInicio().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivosJugadores;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnRegJugador;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelPrincipial;
    // End of variables declaration//GEN-END:variables
}
