/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfasGrafica;

import prog2SO.Juego;

/**
 *
 * @author mjpla
 */
public class VentInicio extends javax.swing.JFrame {
    private VentJugador  vJugador;
    private VentPartida vPartida;
    private VentRanking vRanking;
    private VentTipoTablero vTipoTablero;
    
    /**
     * Creates new form VentInicio
     */
    
    public VentInicio(Juego iJuego) {
        
        initComponents();
        vJugador = new VentJugador();
        vRanking = new VentRanking();
        vTipoTablero = new VentTipoTablero(iJuego);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipial = new javax.swing.JPanel();
        btnRegJugador = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnArchivosJugadores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("VentanaInicio"); // NOI18N
        setSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(null);

        btnRegJugador.setText("Registro de Jugador");
        btnRegJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegJugadorActionPerformed(evt);
            }
        });

        btnJugar.setText("Jugar Partida");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        jButton1.setText("Ranking de Jugadores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnArchivosJugadores.setText("Cargar Archivo de Jugadores");
        btnArchivosJugadores.setName(""); // NOI18N
        btnArchivosJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivosJugadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipialLayout = new javax.swing.GroupLayout(panelPrincipial);
        panelPrincipial.setLayout(panelPrincipialLayout);
        panelPrincipialLayout.setHorizontalGroup(
            panelPrincipialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipialLayout.createSequentialGroup()
                .addGroup(panelPrincipialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipialLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(panelPrincipialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnArchivosJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelPrincipialLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        panelPrincipialLayout.setVerticalGroup(
            panelPrincipialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipialLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnRegJugador)
                .addGap(18, 18, 18)
                .addComponent(btnJugar)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btnArchivosJugadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnSalir))
        );

        getContentPane().add(panelPrincipial);
        panelPrincipial.setBounds(0, 20, 404, 256);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegJugadorActionPerformed
        // TODO add your handling code here:
       vJugador.setVisible(true);
    }//GEN-LAST:event_btnRegJugadorActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        vTipoTablero.setVisible(true);
       // vPartida.setVisible(true);
    }//GEN-LAST:event_btnJugarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        vRanking.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnArchivosJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivosJugadoresActionPerformed
        // TODO add your handling code here:
        //cargar archivo
        
    }//GEN-LAST:event_btnArchivosJugadoresActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSalirActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                //new VentInicio().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivosJugadores;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnRegJugador;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelPrincipial;
    // End of variables declaration//GEN-END:variables
}
