/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfasGrafica;

import Dominio.Juego;
import Dominio.Jugador;
import java.util.Iterator;

/**
 *
 * @author Llote
 */
public class VentJugador extends javax.swing.JFrame {

    private Juego elJuego;
    /**
     * Creates new form VentJugador
     */
    public VentJugador(Juego unJuego) {
        initComponents();
        this.elJuego = unJuego;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtAlias = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        lblAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setToolTipText("");
        txtNombre.setName("txtNombre"); // NOI18N
        getContentPane().add(txtNombre);
        txtNombre.setBounds(150, 110, 164, 22);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Regitro Jugador");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(122, 28, 230, 47);

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 120, 60, 16);

        jLabel3.setText("Alias:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 170, 32, 16);

        jLabel4.setText("Edad:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 220, 33, 16);

        btnRegistrar.setText("Registrar");
        btnRegistrar.setToolTipText("");
        btnRegistrar.setName("btnRegistrar"); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(90, 300, 90, 40);

        btnCancelar.setText("Cancelar");
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(240, 300, 90, 40);

        txtAlias.setName("txtAlias"); // NOI18N
        getContentPane().add(txtAlias);
        txtAlias.setBounds(150, 160, 160, 22);
        getContentPane().add(txtEdad);
        txtEdad.setBounds(150, 220, 60, 22);
        getContentPane().add(lblAviso);
        lblAviso.setBounds(30, 260, 360, 16);

        setBounds(0, 0, 422, 411);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
       
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        if (!this.txtNombre.getText().equals("") && !this.txtAlias.getText().equals("") && !this.txtEdad.getText().equals("")){
            String nombre = this.txtNombre.getText();
            String alias = this.txtAlias.getText();
            int edad = Integer.parseInt(this.txtEdad.getText());
             Jugador unJugador = new Jugador(nombre,alias,edad);
            if (this.elJuego.unicoAlias(alias)){
                this.elJuego.setJugador(unJugador);
            }else{
                Iterator<Jugador> iter = this.elJuego.getJugadores().iterator();
                while( (iter.hasNext())){
                    Jugador aux = iter.next();
                    if (aux.equals(unJugador)) {
                        aux.setEdad(edad);
                        aux.setNombre(nombre);
                    }
                }
            }
            this.lblAviso.setText("Jugador: "+this.txtAlias.getText()+" .Ingresado correctamente.");
            this.limpiarCampos();
        }else{
             this.lblAviso.setText("Los campos de Nombre, Alias o Edad no deben estar vacíos.");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void limpiarCampos(){
        this.txtAlias.setText("");
        this.txtNombre.setText("");
        this.txtEdad.setText("");
    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentJugador().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JTextField txtAlias;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
